CREATE TABLE `email_subscribers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`email` varchar(320) NOT NULL,
	`name` varchar(128),
	`active` boolean NOT NULL DEFAULT true,
	`notifyEpisodes` boolean NOT NULL DEFAULT true,
	`notifyRaceCalls` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`lastEmailedAt` timestamp,
	CONSTRAINT `email_subscribers_id` PRIMARY KEY(`id`),
	CONSTRAINT `email_subscribers_email_unique` UNIQUE(`email`)
);
--> statement-breakpoint
CREATE TABLE `episode_segments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`episodeDate` varchar(10) NOT NULL,
	`segmentKey` varchar(64) NOT NULL,
	`label` varchar(128),
	`emoji` varchar(8),
	`durationSec` float,
	`durationLabel` varchar(16),
	`andrewCdnUrl` text,
	`jennyCdnUrl` text,
	`script` text,
	`sortOrder` int NOT NULL DEFAULT 0,
	`isBreaking` tinyint NOT NULL DEFAULT 0,
	`breakingReason` varchar(256),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `episode_segments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `episodes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`date` varchar(10) NOT NULL,
	`day` varchar(16),
	`friendlyDate` varchar(64),
	`totalDurationSec` int,
	`totalDurationLabel` varchar(16),
	`segmentCount` int,
	`fullEpisodeCdnUrl` text,
	`verificationStatus` enum('passed','warnings','pending') DEFAULT 'pending',
	`verificationWarnings` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `episodes_id` PRIMARY KEY(`id`),
	CONSTRAINT `episodes_date_unique` UNIQUE(`date`)
);
--> statement-breakpoint
CREATE TABLE `governor_races` (
	`id` int AUTO_INCREMENT NOT NULL,
	`state_code` varchar(2) NOT NULL,
	`state_name` varchar(64) NOT NULL,
	`incumbent_name` varchar(128),
	`incumbent_party` enum('D','R','I'),
	`is_open` boolean NOT NULL DEFAULT false,
	`is_term_limited` boolean NOT NULL DEFAULT false,
	`previous_party` enum('D','R','I') NOT NULL,
	`rating` enum('Solid D','Likely D','Lean D','Toss-up','Lean R','Likely R','Solid R') NOT NULL DEFAULT 'Solid R',
	`primary_date` varchar(64),
	`runoff_date` varchar(64),
	`general_date` varchar(64) NOT NULL DEFAULT 'November 3, 2026',
	`is_special` boolean NOT NULL DEFAULT false,
	`status` enum('Scheduled','Voting','Primary Runoff','Called','Certified') NOT NULL DEFAULT 'Scheduled',
	`called_party` enum('D','R','I'),
	`called_winner` varchar(128),
	`called_at` bigint,
	`primary_winner` varchar(128),
	`primary_party` enum('D','R','I'),
	`dem_votes` bigint DEFAULT 0,
	`rep_votes` bigint DEFAULT 0,
	`other_candidate_name` text,
	`other_candidate_party` enum('D','R','I','L','G'),
	`other_votes` bigint DEFAULT 0,
	`other_vote_pct` decimal(5,2),
	`pct_reporting` decimal(5,2) DEFAULT '0',
	`dem_candidate` varchar(128),
	`rep_candidate` varchar(128),
	`dem_previous_office` varchar(256),
	`rep_previous_office` varchar(256),
	`dem_bio` text,
	`rep_bio` text,
	`dem_photo` text,
	`rep_photo` text,
	`notes` text,
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `governor_races_id` PRIMARY KEY(`id`),
	CONSTRAINT `governor_races_state_code_unique` UNIQUE(`state_code`)
);
--> statement-breakpoint
CREATE TABLE `house_races` (
	`id` int AUTO_INCREMENT NOT NULL,
	`state_code` varchar(2) NOT NULL,
	`state_name` varchar(64) NOT NULL,
	`district` int NOT NULL,
	`district_label` varchar(16) NOT NULL,
	`incumbent` varchar(128),
	`incumbent_party` enum('D','R','I'),
	`incumbent_retiring` boolean NOT NULL DEFAULT false,
	`is_vacancy` boolean NOT NULL DEFAULT false,
	`candidate1_name` varchar(128),
	`candidate1_party` enum('D','R','I','L','G'),
	`candidate1_votes` bigint DEFAULT 0,
	`candidate1_vote_pct` decimal(5,2),
	`candidate2_name` varchar(128),
	`candidate2_party` enum('D','R','I','L','G'),
	`candidate2_votes` bigint DEFAULT 0,
	`candidate2_vote_pct` decimal(5,2),
	`called_winner` varchar(128),
	`called_party` enum('D','R','I'),
	`called_at` bigint,
	`primary_winner` varchar(128),
	`primary_party` enum('D','R','I'),
	`other_candidate_name` text,
	`other_candidate_party` enum('D','R','I','L','G'),
	`other_votes` bigint DEFAULT 0,
	`other_vote_pct` decimal(5,2),
	`previous_party` enum('D','R','I'),
	`rating` enum('Solid D','Likely D','Lean D','Toss-up','Lean R','Likely R','Solid R','Safe D','Safe R'),
	`status` enum('Scheduled','Primary','Primary Runoff','General','Called','Certified') NOT NULL DEFAULT 'Scheduled',
	`primary_date` varchar(32),
	`general_date` varchar(32) DEFAULT 'November 3, 2026',
	`pct_reporting` decimal(5,2) DEFAULT '0',
	`candidate1_bio` text,
	`candidate2_bio` text,
	`candidate1_photo` text,
	`candidate2_photo` text,
	`notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `house_races_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `news_cache` (
	`id` int AUTO_INCREMENT NOT NULL,
	`cacheKey` varchar(256) NOT NULL,
	`payload` text,
	`fetchedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `news_cache_id` PRIMARY KEY(`id`),
	CONSTRAINT `news_cache_cacheKey_unique` UNIQUE(`cacheKey`)
);
--> statement-breakpoint
CREATE TABLE `pipeline_runs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`episodeDate` varchar(10) NOT NULL,
	`status` enum('running','success','failed') NOT NULL,
	`triggeredBy` enum('scheduler','manual') NOT NULL DEFAULT 'scheduler',
	`segmentCount` int,
	`totalDurationSec` int,
	`durationMs` int,
	`errorMessage` text,
	`startedAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	CONSTRAINT `pipeline_runs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `podcast_plays` (
	`id` int AUTO_INCREMENT NOT NULL,
	`episodeDate` varchar(10) NOT NULL,
	`segmentKey` varchar(64) NOT NULL,
	`segmentLabel` varchar(128),
	`durationSec` int,
	`listenedSec` int,
	`sessionId` varchar(64),
	`userAgent` varchar(256),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `podcast_plays_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `referendums` (
	`id` int AUTO_INCREMENT NOT NULL,
	`state_code` varchar(2) NOT NULL,
	`state_name` varchar(64) NOT NULL,
	`name` varchar(256) NOT NULL,
	`description` text,
	`category` varchar(128),
	`measure_type` varchar(64),
	`measure_type_full` varchar(256),
	`scope` varchar(16) DEFAULT 'state',
	`country` varchar(128) DEFAULT 'United States',
	`country_code` varchar(3) DEFAULT 'US',
	`yes_label` varchar(128) DEFAULT 'Yes',
	`no_label` varchar(128) DEFAULT 'No',
	`yes_votes` bigint DEFAULT 0,
	`no_votes` bigint DEFAULT 0,
	`pct_reporting` decimal(5,2) DEFAULT '0',
	`election_date` varchar(64) NOT NULL,
	`status` enum('Scheduled','Voting','Called','Certified') NOT NULL DEFAULT 'Scheduled',
	`called_result` enum('Yes','No'),
	`notes` text,
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `referendums_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `senate_races` (
	`id` int AUTO_INCREMENT NOT NULL,
	`state_code` varchar(2) NOT NULL,
	`state_name` varchar(64) NOT NULL,
	`is_special` boolean NOT NULL DEFAULT false,
	`special_note` text,
	`incumbent` varchar(128),
	`incumbent_party` enum('D','R','I'),
	`incumbent_retiring` boolean NOT NULL DEFAULT false,
	`candidate1_name` varchar(128),
	`candidate1_party` enum('D','R','I','L','G'),
	`candidate1_votes` bigint DEFAULT 0,
	`candidate1_vote_pct` decimal(5,2),
	`candidate2_name` varchar(128),
	`candidate2_party` enum('D','R','I','L','G'),
	`candidate2_votes` bigint DEFAULT 0,
	`candidate2_vote_pct` decimal(5,2),
	`called_winner` varchar(128),
	`called_party` enum('D','R','I'),
	`called_at` bigint,
	`primary_winner` varchar(128),
	`primary_party` enum('D','R','I'),
	`other_candidate_name` text,
	`other_candidate_party` enum('D','R','I','L','G'),
	`other_votes` bigint DEFAULT 0,
	`other_vote_pct` decimal(5,2),
	`previous_party` enum('D','R','I'),
	`rating` enum('Solid D','Likely D','Lean D','Toss-up','Lean R','Likely R','Solid R','Safe D','Safe R'),
	`status` enum('Scheduled','Primary','Primary Runoff','General','Called','Certified') NOT NULL DEFAULT 'Scheduled',
	`primary_date` varchar(32),
	`primary_runoff_date` varchar(32),
	`general_date` varchar(32) DEFAULT 'November 3, 2026',
	`pct_reporting` decimal(5,2) DEFAULT '0',
	`candidate1_bio` text,
	`candidate2_bio` text,
	`candidate1_photo` text,
	`candidate2_photo` text,
	`notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `senate_races_id` PRIMARY KEY(`id`)
);
