CREATE TABLE `black_representation_elections` (
	`id` int AUTO_INCREMENT NOT NULL,
	`district` varchar(16) NOT NULL,
	`state` varchar(64) NOT NULL,
	`state_code` varchar(2) NOT NULL,
	`chamber` enum('house','senate','governor') NOT NULL,
	`election_type` enum('primary','runoff','general','special') NOT NULL,
	`party_contest` varchar(16),
	`election_date` varchar(32),
	`result_status` enum('called','too_close_to_call','upcoming','uncontested') NOT NULL DEFAULT 'upcoming',
	`winner_name` varchar(128),
	`winner_party` varchar(8),
	`winner_votes` bigint,
	`winner_vote_pct` decimal(5,2),
	`runner_up_name` varchar(128),
	`runner_up_party` varchar(8),
	`runner_up_votes` bigint,
	`runner_up_vote_pct` decimal(5,2),
	`general_opponent` varchar(128),
	`source_url` text,
	`source_label` varchar(128),
	`article_url` text,
	`redistricting_context` text,
	`notes` text,
	`last_verified_at` timestamp NOT NULL DEFAULT (now()),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `black_representation_elections_id` PRIMARY KEY(`id`)
);
