import { Building2, CalendarDays, Gavel, Layers3, MapPinned, Scale } from "lucide-react";
import { useMemo, useState } from "react";
import { trpc } from "@/lib/trpc";
import { APPORTIONMENT_HISTORY, APPORTIONMENT_YEARS, STATE_CODES } from "@/data/atlasHistory";
import { LEWIS_MANIFEST } from "@/data/atlasBoundaryManifest";

export default function Atlas() {
  const { data: states = [], isLoading } = trpc.election.redistricting.useQuery();
  const [selectedCode, setSelectedCode] = useState<string | null>(() => {
    if (typeof window === "undefined") return null;
    const code = new URLSearchParams(window.location.search).get("state")?.toUpperCase();
    return code && /^[A-Z]{2}$/.test(code) ? code : null;
  });
  const historicalStates = useMemo(() => {
    const activeByName = new Map((states as any[]).map((state) => [state.stateName, state]));
    return Object.keys(APPORTIONMENT_HISTORY).sort().map((stateName) => activeByName.get(stateName) ?? ({ stateCode: STATE_CODES[stateName], stateName, enacted: false, status: "Historical record", method: "Congressional apportionment", delegationBefore: null, projectedImpact: null, litigationNotes: null, reason: null }));
  }, [states]);
  const selected = useMemo(() => historicalStates.find((state: any) => state.stateCode === selectedCode) ?? historicalStates[0], [historicalStates, selectedCode]);
  const history = selected ? APPORTIONMENT_HISTORY[selected.stateName] ?? [1, 1, 1, 1, 1, 1, 1] : [];
  const boundaryEras = selected ? LEWIS_MANIFEST[selected.stateName] ?? [] : [];
  const selectedIsActive = Boolean(selected && (states as any[]).some((state) => state.stateCode === selected.stateCode));
  const litigation = states.filter((state: any) => state.litigationNotes).length;
  const boundaryStates = Object.keys(LEWIS_MANIFEST).length;

  if (isLoading) return <div className="min-h-[70vh] grid place-items-center"><div className="w-9 h-9 rounded-full border-2 border-primary border-t-transparent animate-spin" /></div>;
  return <div className="min-h-screen bg-background text-foreground">
    <section className="border-b border-border bg-[radial-gradient(circle_at_85%_0%,rgba(212,165,82,.14),transparent_33%)]">
      <div className="container py-10">
        <p className="text-primary text-xs uppercase tracking-[0.28em] font-semibold">Congressional geography · 1963–present</p>
        <h1 className="font-display text-4xl sm:text-5xl font-bold mt-3">Historical Atlas</h1>
        <p className="text-muted-foreground mt-3 max-w-3xl">The Atlas explains how representation changes through time: how many House seats each state receives, when its district boundaries changed, and which 2026 maps require present-tense attention. Long-run history and live legal reporting stay deliberately distinct.</p>
        <div className="grid grid-cols-2 sm:grid-cols-5 gap-3 mt-7 max-w-4xl"><Metric value={historicalStates.length} label="State histories" icon={MapPinned}/><Metric value={boundaryStates} label="Boundary archives" icon={Layers3}/><Metric value={states.length} label="Active watchlist" icon={Scale}/><Metric value={litigation} label="With litigation" icon={Gavel}/><Metric value="1963–2025" label="Seat history" icon={CalendarDays}/></div>
        <div className="mt-6 grid gap-3 md:grid-cols-3"><AtlasLens title="Representation size" detail="50-state House apportionment after each decennial cycle."/><AtlasLens title="Boundary eras" detail="Repository-backed congressional district file eras, organized by Congress."/><AtlasLens title="2026 map watch" detail="Live redistricting status, projected impact, and litigation context for active states."/></div>
      </div>
    </section>
    <section className="container py-8 grid xl:grid-cols-[270px_minmax(0,1fr)] gap-6">
      <aside className="rounded-2xl border border-border bg-card overflow-hidden h-fit"><div className="p-4 border-b border-border"><p className="font-semibold">All state histories</p><p className="text-xs text-muted-foreground mt-1">The 50-state apportionment and boundary-era archive; active 2026 watchlist entries retain current map context.</p></div><div className="max-h-[580px] overflow-y-auto divide-y divide-border">{historicalStates.map((state: any) => <button onClick={() => setSelectedCode(state.stateCode)} key={state.stateCode} className={`w-full p-3 text-left flex items-center justify-between transition-colors ${selected?.stateCode === state.stateCode ? "bg-primary/10 text-primary" : "hover:bg-muted/60"}`}><span className="text-sm font-medium">{state.stateName}</span><span className="text-[10px] rounded-full border border-border px-2 py-0.5 text-muted-foreground">{(states as any[]).some((live) => live.stateCode === state.stateCode) ? "2026 watch" : "History"}</span></button>)}</div></aside>
      {selected && <main className="space-y-6">
        <div className="rounded-2xl border border-border bg-card p-5 sm:p-7"><div className="flex flex-col sm:flex-row justify-between gap-4"><div><p className="text-primary text-xs tracking-[.18em] uppercase">{selected.stateCode} · {selectedIsActive ? "2026 watchlist" : "historical record"}</p><h2 className="font-display text-3xl font-bold mt-2">{selected.stateName}</h2><p className="text-muted-foreground mt-2 max-w-2xl">{selected.reason || "A 1963–2025 congressional apportionment record from the original Historical Atlas."}</p></div><div className="rounded-xl border border-border bg-background p-3 h-fit text-sm"><span className="text-muted-foreground block text-xs">{selectedIsActive ? "Current map status" : "Coverage"}</span><strong>{selectedIsActive ? selected.status || "Monitoring" : "Historical apportionment"}</strong></div></div><div className="grid md:grid-cols-4 gap-3 mt-6"><Info label="Method" value={selected.method || "Congressional apportionment"} icon={Scale}/><Info label="Delegation before" value={selected.delegationBefore || "See seat history"} icon={Building2}/><Info label="Projected impact" value={selected.projectedImpact || "No active 2026 map change"} icon={Layers3}/><Info label="Boundary eras" value={boundaryEras.length ? `${boundaryEras.length} repository files` : "Not catalogued"} icon={MapPinned}/></div></div>
        <div className="rounded-2xl border border-border bg-card p-5 sm:p-7"><div className="flex justify-between items-end"><div><h3 className="font-display text-xl font-bold">Apportionment history</h3><p className="text-sm text-muted-foreground mt-1">House seats following each decennial redistricting cycle, retained from the original Atlas coverage.</p></div><span className="text-primary font-display text-2xl font-bold">{history[history.length - 1]}</span></div><SeatChart values={history}/><div className="grid grid-cols-7 gap-1 mt-2 text-[10px] text-muted-foreground text-center">{APPORTIONMENT_YEARS.map((year) => <span key={year}>{year}</span>)}</div></div>
        <div className="grid lg:grid-cols-2 gap-6"><div className="rounded-2xl border border-border bg-card p-5"><h3 className="font-display text-xl font-bold">Current delegation grid</h3><p className="text-sm text-muted-foreground mt-1">A compact district index for the current apportionment—not a substitute for the legal district boundary file.</p><div className="grid grid-cols-6 sm:grid-cols-8 gap-2 mt-5">{Array.from({ length: history.at(-1) || 1 }).map((_, index) => <div key={index} className="aspect-square rounded-md border border-primary/25 bg-primary/10 grid place-items-center text-xs font-semibold text-primary">{index + 1}</div>)}</div></div><div className="rounded-2xl border border-border bg-card p-5"><h3 className="font-display text-xl font-bold">Redistricting notes</h3><p className="text-sm text-muted-foreground mt-3 leading-relaxed">{selected.litigationNotes || (selectedIsActive ? "No litigation notes are currently tracked for this state." : "This state is outside the active 2026 watchlist; the Atlas retains its congressional-apportionment history.")}</p><p className="text-sm text-muted-foreground mt-4 leading-relaxed">{selected.reason || "The boundary archive below preserves each state’s historical congressional district file eras. Party-control and representative timelines would require a separate, verified source dataset before they can be added."}</p></div></div>
        <div className="rounded-2xl border border-border bg-card p-5 sm:p-7"><div className="flex flex-wrap items-end justify-between gap-3"><div><h3 className="font-display text-xl font-bold">Boundary-era archive</h3><p className="mt-1 text-sm text-muted-foreground">Original repository district-file eras for {selected.stateName}, indexed by Congress. These are archive references, not a substitute for official current legal maps.</p></div><span className="rounded-full border border-primary/25 bg-primary/10 px-3 py-1 text-xs font-semibold text-primary">{boundaryEras.length} eras</span></div>{boundaryEras.length ? <div className="mt-5 grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{boundaryEras.map((era) => <div key={era.name} className="rounded-lg border border-border bg-background p-3"><p className="text-sm font-medium">{era.start}th–{era.end}th Congress</p><p className="mt-1 break-all text-xs text-muted-foreground">{era.name}</p></div>)}</div> : <p className="mt-5 text-sm text-muted-foreground">No boundary-era manifest entry is currently available for this state.</p>}</div>
      </main>}
    </section>
  </div>;
}

function Metric({ value, label, icon: Icon }: { value: string | number; label: string; icon: any }) { return <div className="rounded-xl border border-border bg-card/80 px-4 py-3"><Icon size={16} className="text-primary mb-2"/><div className="font-display text-xl font-bold">{value}</div><div className="text-[10px] text-muted-foreground uppercase tracking-wide">{label}</div></div>; }
function Info({ label, value, icon: Icon }: { label: string; value: string; icon: any }) { return <div className="rounded-lg border border-border bg-background p-3"><Icon size={15} className="text-primary mb-2"/><p className="text-[10px] uppercase tracking-wide text-muted-foreground">{label}</p><p className="text-sm font-medium mt-1">{value}</p></div>; }
function AtlasLens({ title, detail }: { title: string; detail: string }) { return <div className="rounded-xl border border-primary/15 bg-card/70 p-4"><p className="text-xs font-bold uppercase tracking-[.13em] text-primary">{title}</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{detail}</p></div>; }
function SeatChart({ values }: { values: number[] }) { const max = Math.max(...values, 1); return <div className="h-52 mt-6 flex items-end gap-2">{values.map((value, index) => <div key={index} className="flex-1 h-full flex flex-col justify-end"><span className="text-xs text-center text-muted-foreground mb-1">{value}</span><div className="rounded-t-md bg-primary/75 min-h-2 transition-all" style={{ height: `${Math.max(8, (value / max) * 100)}%` }} /></div>)}</div>; }
