import { useMemo } from "react";
import { Link } from "wouter";
import { ArrowRight, BookOpenText, Building2, ExternalLink, Landmark, Scale, ShieldCheck, Vote } from "lucide-react";
import { trpc } from "@/lib/trpc";

const DOJ_VOTING_URL = "https://www.justice.gov/crt/voting-section";
const CENSUS_APPORTIONMENT_URL = "https://www.census.gov/topics/public-sector/congressional-apportionment.html";
const NASS_URL = "https://www.nass.org/";

function cleanText(value?: string) {
  return (value ?? "").replace(/<[^>]*>/g, "").replace(/&amp;/g, "&").replace(/&#8217;/g, "’").replace(/&#8211;/g, "–").trim();
}

function dateLabel(value?: string) {
  if (!value) return "Source date unavailable";
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? "Source date unavailable" : date.toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" });
}

export default function PowerContext() {
  const newsInput = useMemo(() => ({ page: 1, perPage: 6 }), []);
  const { data: news } = trpc.news.list.useQuery(newsInput);
  const { data: senate = [] } = trpc.election.senate.useQuery();
  const { data: governors = [] } = trpc.election.governors.useQuery();
  const { data: representation = [] } = trpc.election.cbc.useQuery();
  const { data: representationElections = [] } = trpc.election.blackRepresentationElections.useQuery();
  const { data: redistricting = [] } = trpc.election.redistricting.useQuery();
  const stories = (news?.posts ?? []) as any[];
  const liveRecords = [...(senate as any[]).slice(0, 3), ...(governors as any[]).slice(0, 3)];

  return <div className="min-h-screen bg-background text-foreground">
    <section className="border-b border-border bg-[radial-gradient(circle_at_82%_0%,rgba(212,165,82,.19),transparent_34%),radial-gradient(circle_at_12%_100%,rgba(27,102,130,.16),transparent_30%)]">
      <div className="container py-12 sm:py-16"><p className="text-primary text-xs font-semibold uppercase tracking-[.25em]">Black Politics Now · Power Context</p><h1 className="font-display mt-4 max-w-5xl text-4xl font-bold tracking-tight sm:text-6xl">Reporting connected to the races, institutions, and history shaping power today.</h1><p className="mt-5 max-w-3xl text-base leading-7 text-muted-foreground sm:text-lg">Black Politics Now brings reporting into conversation with verified election records, the institutions that govern representation, and the historical maps that reveal how power changes. It does not automatically declare a story-to-record relationship: direct links require editorial review.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/elections" className="inline-flex items-center gap-2 rounded-md bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground no-underline"><Vote size={16}/>Explore 2026 races</Link><Link href="/atlas" className="inline-flex items-center gap-2 rounded-md border border-primary/35 bg-primary/10 px-4 py-2.5 text-sm font-semibold text-primary no-underline"><Landmark size={16}/>Travel the Historical Atlas</Link><Link href="/research" className="inline-flex items-center gap-2 rounded-md border border-border px-4 py-2.5 text-sm font-semibold text-foreground no-underline"><BookOpenText size={16}/>Research Desk</Link></div></div>
    </section>

    <section className="container py-8"><div className="grid gap-4 lg:grid-cols-4"><PowerStep icon={BookOpenText} title="Report" detail="Original Black Politics Now reporting preserves the editorial record."/><PowerStep icon={Vote} title="Race" detail="Election records clarify which contests and representation are at stake."/><PowerStep icon={Building2} title="Institution" detail="Public agencies, courts, and state election officials shape the rules."/><PowerStep icon={Landmark} title="History" detail="Apportionment and boundary eras explain how representation arrived here."/></div><div className="mt-4 rounded-xl border border-primary/25 bg-primary/10 p-4 text-sm leading-6 text-foreground"><ShieldCheck size={17} className="mr-2 inline text-primary"/><strong>Editorial safeguard:</strong> this is a context framework, not an automated attribution engine. Reporting always links to its original source; election and Atlas records retain their own sources; only editor-confirmed relationships may become direct public story-to-record links.</div></section>

    <section className="container pb-8"><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4"><Metric value={stories.length || "—"} label="Current reporting sources" detail="Latest original newsroom entries"/><Metric value={(senate as any[]).length + (governors as any[]).length} label="Top-of-ticket race records" detail="Senate and governor entries"/><Metric value={(representation as any[]).length} label="Black representation profiles" detail={`${(representationElections as any[]).length} article-backed election records`}/><Metric value={(redistricting as any[]).length} label="Active map watch records" detail="Live redistricting context"/></div></section>

    <section className="container grid gap-6 pb-8 xl:grid-cols-[minmax(0,1.45fr)_minmax(360px,0.85fr)]"><div className="rounded-2xl border border-border bg-card p-5 sm:p-7"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-primary text-xs font-semibold uppercase tracking-[.17em]">Reporting desk</p><h2 className="font-display mt-2 text-2xl font-bold">What Black Politics Now is reporting</h2><p className="mt-2 text-sm text-muted-foreground">Each entry opens the original source. Context is supplied alongside—not substituted for—reporting.</p></div><a href="https://blkpoliticsnow.com" target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-sm font-semibold text-primary underline underline-offset-4">Original newsroom <ExternalLink size={14}/></a></div><div className="mt-5 divide-y divide-border">{stories.slice(0, 5).map((story) => <a key={story.id} href={story.link} target="_blank" rel="noreferrer" className="group grid gap-3 py-4 no-underline sm:grid-cols-[92px_1fr_auto]"><div className="hidden overflow-hidden rounded bg-muted sm:block">{story.imageUrl ? <img src={story.imageUrl} alt="" className="h-[62px] w-full object-cover"/> : <div className="h-[62px] bg-primary/10"/>}</div><div><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-primary">Original reporting · {dateLabel(story.date)}</p><h3 className="mt-1 text-base font-semibold leading-6 text-foreground transition-colors group-hover:text-primary">{cleanText(story.title?.rendered ?? story.title)}</h3></div><ArrowRight size={17} className="hidden self-center text-muted-foreground transition-transform group-hover:translate-x-1 sm:block"/></a>)}{!stories.length && <p className="py-8 text-sm text-muted-foreground">The original newsroom feed is temporarily unavailable. The reporting layer will return with the next verified source snapshot.</p>}</div></div>
      <div className="space-y-6"><div className="rounded-2xl border border-border bg-card p-5"><p className="text-primary text-xs font-semibold uppercase tracking-[.17em]">Election record</p><h2 className="font-display mt-2 text-xl font-bold">Races and representation</h2><p className="mt-2 text-sm text-muted-foreground">Verified public records remain distinct from editorial interpretation.</p><div className="mt-4 space-y-2">{liveRecords.map((race: any) => <Link href="/elections" key={`${race.stateCode}-${race.id}`} className="block rounded-lg border border-border bg-background p-3 no-underline transition-colors hover:border-primary/40"><div className="flex items-center justify-between gap-2"><span className="text-xs font-semibold text-foreground">{race.stateName} · {race.chamber ?? race.office ?? "Statewide race"}</span><span className="rounded-full bg-primary/10 px-2 py-0.5 text-[10px] font-semibold text-primary">{race.rating ?? "Monitoring"}</span></div><p className="mt-1 text-xs text-muted-foreground">{race.candidate1 || race.candidateName || "Candidate details in the Election Map"}</p></Link>)}{!liveRecords.length && <p className="text-sm text-muted-foreground">Race records are loading.</p>}</div><Link href="/elections" className="mt-4 inline-flex items-center gap-1 text-sm font-semibold text-primary no-underline">Open Election Map <ArrowRight size={14}/></Link></div>
      <div className="rounded-2xl border border-border bg-card p-5"><p className="text-primary text-xs font-semibold uppercase tracking-[.17em]">Institutional record</p><h2 className="font-display mt-2 text-xl font-bold">How power is governed</h2><div className="mt-4 space-y-3"><InstitutionLink href={DOJ_VOTING_URL} title="Voting Rights Act enforcement" detail="DOJ Civil Rights Division · Voting Section"/><InstitutionLink href={CENSUS_APPORTIONMENT_URL} title="Congressional apportionment" detail="U.S. Census Bureau · state representation"/><InstitutionLink href={NASS_URL} title="Election administration" detail="National Association of Secretaries of State"/></div></div></div></section>

    <section className="border-t border-border bg-muted/20"><div className="container grid gap-6 py-10 lg:grid-cols-[1.2fr_.8fr]"><div><p className="text-primary text-xs font-semibold uppercase tracking-[.17em]">Historical lens</p><h2 className="font-display mt-2 text-2xl font-bold">A boundary is not just a line.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">The Historical Atlas makes changes to representation visible across time, pairing congressional district boundaries with state apportionment and current redistricting records. It is the historical context layer behind the platform’s contemporary reporting and race tracker.</p></div><div className="flex items-center justify-start lg:justify-end"><Link href="/atlas" className="inline-flex items-center gap-2 rounded-md border border-primary/35 bg-primary/10 px-4 py-3 text-sm font-semibold text-primary no-underline"><Scale size={17}/>Open Historical Atlas <ArrowRight size={15}/></Link></div></div></section>
  </div>;
}

function PowerStep({ icon: Icon, title, detail }: { icon: any; title: string; detail: string }) { return <div className="rounded-xl border border-border bg-card p-4"><Icon size={18} className="text-primary"/><p className="mt-4 text-xs font-semibold uppercase tracking-[.16em] text-primary">{title}</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{detail}</p></div>; }
function Metric({ value, label, detail }: { value: number | string; label: string; detail: string }) { return <div className="rounded-xl border border-border bg-card p-4"><p className="font-display text-3xl font-bold text-primary">{value}</p><p className="mt-1 text-xs font-semibold uppercase tracking-[.13em] text-foreground">{label}</p><p className="mt-2 text-xs leading-5 text-muted-foreground">{detail}</p></div>; }
function InstitutionLink({ href, title, detail }: { href: string; title: string; detail: string }) { return <a href={href} target="_blank" rel="noreferrer" className="group block rounded-lg border border-border bg-background p-3 no-underline transition-colors hover:border-primary/40"><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-semibold text-foreground group-hover:text-primary">{title}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div><ExternalLink size={14} className="shrink-0 text-primary"/></div></a>; }
