import { AlertTriangle, CheckCircle2, Clock3, FileDiff, Radio, ShieldCheck, UserRoundCheck } from "lucide-react";
import { trpc } from "@/lib/trpc";

function toneFor(severity: string) {
  return severity === "high" ? "border-red-500/35 bg-red-500/10 text-red-700 dark:text-red-300" : "border-amber-500/35 bg-amber-500/10 text-amber-700 dark:text-amber-300";
}

export function ElectionDayCommandCenterTab() {
  const { data, isLoading, refetch, dataUpdatedAt } = trpc.electionDay.commandCenter.useQuery(undefined, { refetchInterval: 30_000 });
  if (isLoading || !data) return <div className="space-y-4"><div className="h-36 rounded-xl bg-muted animate-pulse" /><div className="h-64 rounded-xl bg-muted animate-pulse" /></div>;
  const { heartbeat, coverage, triage, runbook } = data as any;
  const active = heartbeat.mode === "active" && heartbeat.sourceHealth === "healthy" && !heartbeat.stale;
  return <div className="space-y-5">
    <section className="glass-card rounded-xl p-5">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-primary">Protected operations</p><h2 className="mt-1 flex items-center gap-2 text-lg font-bold"><Radio size={18} className="text-primary" /> Election Day Command Center</h2><p className="mt-1 max-w-3xl text-sm text-muted-foreground">A review-first view of polling health, race coverage, exceptions, and required operator steps. It does not call races, publish results, or apply corrections.</p></div><button onClick={() => refetch()} className="rounded-md border border-border px-3 py-2 text-xs font-semibold hover:bg-muted">Refresh snapshot</button></div>
      <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatusMetric icon={active ? CheckCircle2 : AlertTriangle} label="Source heartbeat" value={active ? "Healthy" : heartbeat.mode === "standby" ? "Standby" : heartbeat.stale ? "Stale" : "Review needed"} detail={`${heartbeat.sourceName} · ${heartbeat.ageMinutes === null ? "no recent tick" : `${heartbeat.ageMinutes} min ago`}`} good={active} /><StatusMetric icon={Clock3} label="Engine state" value={heartbeat.mode} detail={heartbeat.activeDate ? `Active date: ${heartbeat.activeDate}` : heartbeat.lastSummary ?? "Awaiting an active election date"} good={heartbeat.mode !== "degraded"} /><StatusMetric icon={ShieldCheck} label="Mapped coverage" value={`${coverage.mapped} races`} detail={`${coverage.reporting} reporting · ${coverage.called} called`} good /><StatusMetric icon={FileDiff} label="Review queue" value={`${triage.length} items`} detail={`${coverage.pendingChangeSets} change sets awaiting review`} good={triage.length === 0} /></div>
      <p className="mt-4 text-xs text-muted-foreground">Last dashboard refresh: {dataUpdatedAt ? new Date(dataUpdatedAt).toLocaleTimeString([], { hour: "numeric", minute: "2-digit", second: "2-digit" }) : "Awaiting sync"}. <strong className="text-foreground">Source note:</strong> {heartbeat.lastSummary ?? "No heartbeat detail is available yet."}</p>
    </section>
    <section className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]">
      <div className="glass-card rounded-xl p-5"><div className="flex items-center justify-between gap-3"><div><h3 className="text-sm font-bold uppercase tracking-wider">Race triage queue</h3><p className="mt-1 text-xs text-muted-foreground">Source-health alerts, candidate coverage gaps, and high-priority review work.</p></div><span className="rounded-full bg-primary/10 px-2 py-1 text-xs font-semibold text-primary">{triage.length} open</span></div><div className="mt-4 space-y-2">{triage.length ? triage.map((item: any, index: number) => <article key={`${item.title}-${index}`} className={`rounded-lg border p-3 ${toneFor(item.severity)}`}><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold">{item.title}</p><p className="mt-1 text-xs opacity-90">{item.detail}</p></div><span className="shrink-0 rounded bg-background/45 px-1.5 py-0.5 text-[10px] font-bold uppercase">{item.type}</span></div><p className="mt-2 text-xs font-medium">Next: {item.action}</p></article>) : <p className="rounded-lg border border-dashed border-border px-4 py-6 text-center text-sm text-muted-foreground">No active triage items. Keep monitoring the source heartbeat and review queues.</p>}</div></div>
      <div className="glass-card rounded-xl p-5"><h3 className="text-sm font-bold uppercase tracking-wider">Election Day runbook</h3><p className="mt-1 text-xs text-muted-foreground">An operator checklist; each public action remains separately reviewed.</p><div className="mt-4 space-y-4">{runbook.map((item: any) => <div key={item.step} className="flex gap-3"><span className="grid h-6 w-6 shrink-0 place-items-center rounded-full bg-primary/10 text-xs font-bold text-primary">{item.step}</span><div><p className="text-sm font-semibold">{item.title}</p><p className="mt-1 text-xs leading-relaxed text-muted-foreground">{item.detail}</p></div></div>)}</div></div>
    </section>
    <section className="glass-card rounded-xl p-5"><h3 className="text-sm font-bold uppercase tracking-wider">Coverage and review guards</h3><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Guard label="Senate mapped" value={coverage.senate} /><Guard label="House mapped" value={coverage.house} /><Guard label="Governor mapped" value={coverage.governor} /><Guard label="Candidate gaps" value={coverage.candidateGaps} warn={coverage.candidateGaps > 0} /></div><div className="mt-4 rounded-lg border border-border/70 bg-background/50 p-3 text-xs text-muted-foreground"><UserRoundCheck className="mr-1 inline text-primary" size={13} /> A source heartbeat or triage item is an operational signal only. It cannot call a race, send a public alert, publish a result, or apply a correction without explicit administrator review.</div></section>
  </div>;
}

function StatusMetric({ icon: Icon, label, value, detail, good }: { icon: any; label: string; value: string; detail: string; good: boolean }) {
  return <div className="rounded-lg border border-border/70 bg-background/45 p-3"><div className="flex items-center gap-2 text-muted-foreground"><Icon size={15} className={good ? "text-emerald-600 dark:text-emerald-300" : "text-amber-600 dark:text-amber-300"} /><span className="text-[10px] font-bold uppercase tracking-wider">{label}</span></div><p className="mt-2 text-lg font-bold capitalize">{value}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div>;
}

function Guard({ label, value, warn = false }: { label: string; value: number; warn?: boolean }) { return <div className="rounded-lg border border-border/70 bg-background/45 p-3"><p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">{label}</p><p className={`mt-2 text-xl font-bold ${warn ? "text-amber-700 dark:text-amber-300" : "text-foreground"}`}>{value}</p></div>; }
