import { useEffect, useMemo, useState } from "react";
import { BarChart3, CheckCircle2, Code2, Copy, ExternalLink, FileText, Headphones, Rss, Sparkles } from "lucide-react";
import { trpc } from "@/lib/trpc";

const fieldClass = "mt-1 w-full rounded-md border border-border bg-background px-3 py-2 text-xs text-foreground outline-none focus:ring-1 focus:ring-primary";

export function PodcastPublishingKit() {
  const { data: episodes = [] } = trpc.podcast.getEpisodes.useQuery();
  const [episodeDate, setEpisodeDate] = useState("");
  const [copyState, setCopyState] = useState("");
  const { data: notes, refetch: refetchNotes } = trpc.podcast.getShowNotes.useQuery({ episodeDate }, { enabled: Boolean(episodeDate) });
  const { data: analytics } = trpc.podcast.analytics.useQuery({ days: 30 });
  const buildNotes = trpc.podcast.buildShowNotes.useMutation({ onSuccess: () => void refetchNotes() });
  const saveNotes = trpc.podcast.saveShowNotes.useMutation({ onSuccess: () => void refetchNotes() });
  const [draft, setDraft] = useState({ title: "", summary: "", showNotes: "", keywords: "" });

  useEffect(() => { if (!episodeDate && episodes[0]) setEpisodeDate((episodes[0] as any).date); }, [episodes, episodeDate]);
  useEffect(() => { if (notes) setDraft({ title: notes.title, summary: notes.summary, showNotes: notes.showNotes, keywords: notes.keywords }); }, [notes]);

  const origin = typeof window === "undefined" ? "" : window.location.origin;
  const embedCode = useMemo(() => `<iframe src="${origin}/embed${episodeDate ? `?episode=${episodeDate}` : ""}" width="100%" height="210" frameborder="0" allow="autoplay" title="Daily Intelligence Brief"></iframe>`, [origin, episodeDate]);
  const copy = async (value: string, label: string) => { await navigator.clipboard.writeText(value); setCopyState(`${label} copied`); window.setTimeout(() => setCopyState(""), 2000); };

  return <section className="glass-card rounded-xl p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-primary">Legacy publishing toolkit</p><h3 className="mt-1 text-base font-bold">Distribution, show notes, and listener analytics</h3><p className="mt-1 max-w-2xl text-xs leading-5 text-muted-foreground">Source-grounded show-note drafts, a portable player, RSS access, and privacy-limited play metrics. Editorial text remains editable before external reuse.</p></div>{copyState && <span className="rounded-full bg-emerald-500/10 px-2.5 py-1 text-xs font-semibold text-emerald-700 dark:text-emerald-300">{copyState}</span>}</div>
    <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Headphones} label="30-day plays" value={analytics?.totalPlays ?? 0}/><Metric icon={BarChart3} label="Anonymous listeners" value={analytics?.uniqueSessions ?? 0}/><Metric icon={Headphones} label="Full episodes" value={analytics?.fullEpisodePlays ?? 0}/><Metric icon={FileText} label="Segment plays" value={analytics?.segmentPlays ?? 0}/></div>
    <div className="mt-5 grid gap-4 xl:grid-cols-2"><div className="rounded-xl border border-border bg-background/55 p-4"><div className="flex items-center gap-2"><Rss size={15} className="text-primary"/><h4 className="text-sm font-semibold">Podcast distribution</h4></div><p className="mt-1 text-xs leading-5 text-muted-foreground">The integrated RSS feed can be submitted to listening directories. The portable player preserves the same current episode context.</p><div className="mt-3 space-y-2"><CopyRow label="RSS feed" value={`${origin}/api/rss`} onCopy={() => copy(`${origin}/api/rss`, "RSS URL")} onOpen={`${origin}/api/rss`}/><CopyRow label="Embed player" value={embedCode} onCopy={() => copy(embedCode, "Embed code")}/></div></div>
      <div className="rounded-xl border border-border bg-background/55 p-4"><div className="flex items-center gap-2"><Code2 size={15} className="text-primary"/><h4 className="text-sm font-semibold">Listener interest</h4></div><p className="mt-1 text-xs leading-5 text-muted-foreground">Playback starts record a hashed, session-scoped event only. No IP address, raw user agent, or account identity is stored.</p><div className="mt-3 space-y-2">{analytics?.topEpisodes?.length ? analytics.topEpisodes.slice(0, 3).map((row) => <div key={row.episodeDate} className="flex items-center justify-between rounded-lg border border-border/70 px-3 py-2 text-xs"><span className="font-medium text-foreground">{row.episodeDate}</span><span className="font-semibold text-primary">{row.plays} plays</span></div>) : <p className="rounded-lg border border-dashed border-border px-3 py-4 text-xs text-muted-foreground">Play analytics will appear as listeners use the integrated player.</p>}</div></div></div>
    <div className="mt-5 rounded-xl border border-border bg-background/55 p-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><div className="flex items-center gap-2"><Sparkles size={15} className="text-primary"/><h4 className="text-sm font-semibold">Source-grounded episode show notes</h4></div><p className="mt-1 text-xs text-muted-foreground">Drafted only from the stored episode structure and cited segment-source names, then saved as an editor-controlled publishing record.</p></div><select value={episodeDate} onChange={(event) => setEpisodeDate(event.target.value)} className="rounded-md border border-border bg-background px-3 py-2 text-xs">{(episodes as any[]).map((episode) => <option key={episode.date} value={episode.date}>{episode.friendlyDate || episode.date}</option>)}</select></div>
      <div className="mt-4 grid gap-3"><label className="text-xs font-semibold">Title<input value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} className={fieldClass}/></label><label className="text-xs font-semibold">Summary<textarea value={draft.summary} onChange={(event) => setDraft({ ...draft, summary: event.target.value })} rows={3} className={fieldClass}/></label><label className="text-xs font-semibold">Show notes<textarea value={draft.showNotes} onChange={(event) => setDraft({ ...draft, showNotes: event.target.value })} rows={6} className={fieldClass}/></label><label className="text-xs font-semibold">Keywords<input value={draft.keywords} onChange={(event) => setDraft({ ...draft, keywords: event.target.value })} className={fieldClass}/></label></div>
      <div className="mt-4 flex flex-wrap gap-2"><button onClick={() => episodeDate && buildNotes.mutate({ episodeDate })} disabled={!episodeDate || buildNotes.isPending} className="rounded-md border border-primary/30 bg-primary/10 px-3 py-2 text-xs font-semibold text-primary disabled:opacity-50">{buildNotes.isPending ? "Building…" : "Build from episode record"}</button><button onClick={() => episodeDate && saveNotes.mutate({ episodeDate, ...draft })} disabled={!episodeDate || saveNotes.isPending || !draft.title || !draft.summary || !draft.showNotes} className="inline-flex items-center gap-1 rounded-md bg-primary px-3 py-2 text-xs font-semibold text-primary-foreground disabled:opacity-50"><CheckCircle2 size={13}/>{saveNotes.isPending ? "Saving…" : "Save editorial notes"}</button>{(buildNotes.error || saveNotes.error) && <p className="text-xs text-red-700 dark:text-red-300">{buildNotes.error?.message || saveNotes.error?.message}</p>}</div>
    </div>
  </section>;
}

function Metric({ icon: Icon, label, value }: { icon: any; label: string; value: number }) { return <div className="rounded-lg border border-border bg-background/50 p-3"><Icon size={15} className="text-primary"/><p className="mt-2 text-lg font-bold text-foreground">{value.toLocaleString()}</p><p className="text-[10px] font-bold uppercase tracking-[0.1em] text-muted-foreground">{label}</p></div>; }
function CopyRow({ label, value, onCopy, onOpen }: { label: string; value: string; onCopy: () => void; onOpen?: string }) { return <div className="flex items-center gap-2"><div className="min-w-0 flex-1 truncate rounded-md border border-border bg-muted/50 px-2 py-2 font-mono text-[10px] text-muted-foreground">{value}</div><button onClick={onCopy} className="rounded-md border border-border p-2 text-foreground hover:bg-muted" title={`Copy ${label}`}><Copy size={13}/></button>{onOpen && <a href={onOpen} target="_blank" rel="noreferrer" className="rounded-md border border-border p-2 text-foreground hover:bg-muted" title={`Open ${label}`}><ExternalLink size={13}/></a>}</div>; }
